<?php

namespace Database\Seeders;

use App\Models\Hostel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HostelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hostels = [
            [
                'name' => 'Sunrise Hostel',
                'description' => 'A modern, comfortable hostel located in the heart of the city. Perfect for students and young professionals.',
                'address' => '123 Main Street',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'USA',
                'postal_code' => '10001',
                'phone' => '+1-555-0123',
                'email' => 'info@sunrisehostel.com',
                'website' => 'https://sunrisehostel.com',
                'total_rooms' => 50,
                'total_beds' => 200,
                'rent_per_bed' => 450.00,
                'amenities' => ['WiFi', 'Laundry', 'Kitchen', 'Common Room', 'Parking', 'Security'],
                'images' => ['hostel1.jpg', 'hostel2.jpg', 'hostel3.jpg'],
                'status' => 'active',
                'manager_name' => 'John Smith',
                'manager_phone' => '+1-555-0123',
                'manager_email' => 'john@sunrisehostel.com',
                'rules' => 'No smoking, No pets, Quiet hours 10 PM - 7 AM, Visitors must be registered',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
            ],
            [
                'name' => 'Downtown Dormitory',
                'description' => 'Located in the bustling downtown area, this hostel offers easy access to public transportation and city attractions.',
                'address' => '456 Oak Avenue',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'country' => 'USA',
                'postal_code' => '90210',
                'phone' => '+1-555-0456',
                'email' => 'info@downtowndorm.com',
                'website' => 'https://downtowndorm.com',
                'total_rooms' => 75,
                'total_beds' => 300,
                'rent_per_bed' => 520.00,
                'amenities' => ['WiFi', 'Laundry', 'Kitchen', 'Common Room', 'Parking', 'Security', 'Gym', 'Study Room'],
                'images' => ['downtown1.jpg', 'downtown2.jpg', 'downtown3.jpg'],
                'status' => 'active',
                'manager_name' => 'Sarah Johnson',
                'manager_phone' => '+1-555-0456',
                'manager_email' => 'sarah@downtowndorm.com',
                'rules' => 'No smoking, No pets, Quiet hours 11 PM - 7 AM, Visitors must be registered, No parties after 10 PM',
                'check_in_time' => '15:00:00',
                'check_out_time' => '11:00:00',
            ],
            [
                'name' => 'Campus Corner',
                'description' => 'Perfect for students attending nearby universities. Close to campus with study-friendly environment.',
                'address' => '789 University Blvd',
                'city' => 'Chicago',
                'state' => 'IL',
                'country' => 'USA',
                'postal_code' => '60601',
                'phone' => '+1-555-0789',
                'email' => 'info@campuscorner.com',
                'website' => 'https://campuscorner.com',
                'total_rooms' => 40,
                'total_beds' => 160,
                'rent_per_bed' => 380.00,
                'amenities' => ['WiFi', 'Laundry', 'Kitchen', 'Common Room', 'Study Room', 'Library', 'Cafeteria'],
                'images' => ['campus1.jpg', 'campus2.jpg', 'campus3.jpg'],
                'status' => 'maintenance',
                'manager_name' => 'Mike Davis',
                'manager_phone' => '+1-555-0789',
                'manager_email' => 'mike@campuscorner.com',
                'rules' => 'No smoking, No pets, Quiet hours 9 PM - 7 AM, Study hours enforced, Visitors must be registered',
                'check_in_time' => '14:00:00',
                'check_out_time' => '10:00:00',
            ],
            [
                'name' => 'Metro Residence',
                'description' => 'Modern hostel with excellent metro connectivity. Ideal for professionals and travelers.',
                'address' => '321 Metro Street',
                'city' => 'Houston',
                'state' => 'TX',
                'country' => 'USA',
                'postal_code' => '77001',
                'phone' => '+1-555-0321',
                'email' => 'info@metroresidence.com',
                'website' => 'https://metroresidence.com',
                'total_rooms' => 60,
                'total_beds' => 240,
                'rent_per_bed' => 420.00,
                'amenities' => ['WiFi', 'Laundry', 'Kitchen', 'Common Room', 'Parking', 'Security', 'Air Conditioning', 'Cleaning Service'],
                'images' => ['metro1.jpg', 'metro2.jpg', 'metro3.jpg'],
                'status' => 'inactive',
                'manager_name' => 'Lisa Wilson',
                'manager_phone' => '+1-555-0321',
                'manager_email' => 'lisa@metroresidence.com',
                'rules' => 'No smoking, No pets, Quiet hours 10 PM - 7 AM, Visitors must be registered, Professional environment',
                'check_in_time' => '16:00:00',
                'check_out_time' => '11:00:00',
            ],
            [
                'name' => 'Garden View Hostel',
                'description' => 'Peaceful hostel with beautiful garden views. Perfect for those seeking a quiet environment.',
                'address' => '555 Garden Lane',
                'city' => 'Seattle',
                'state' => 'WA',
                'country' => 'USA',
                'postal_code' => '98101',
                'phone' => '+1-555-0555',
                'email' => 'info@gardenviewhostel.com',
                'website' => 'https://gardenviewhostel.com',
                'total_rooms' => 35,
                'total_beds' => 140,
                'rent_per_bed' => 480.00,
                'amenities' => ['WiFi', 'Laundry', 'Kitchen', 'Common Room', 'Garden', 'Parking', 'Security'],
                'images' => ['garden1.jpg', 'garden2.jpg', 'garden3.jpg'],
                'status' => 'active',
                'manager_name' => 'Emma Thompson',
                'manager_phone' => '+1-555-0555',
                'manager_email' => 'emma@gardenviewhostel.com',
                'rules' => 'No smoking, No pets, Quiet hours 10 PM - 7 AM, Garden access during daylight hours only',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
            ],
            [
                'name' => 'Tech Hub Residence',
                'description' => 'Modern hostel designed for tech professionals and digital nomads. High-speed internet and co-working spaces.',
                'address' => '888 Innovation Drive',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'postal_code' => '94102',
                'phone' => '+1-555-0888',
                'email' => 'info@techhubresidence.com',
                'website' => 'https://techhubresidence.com',
                'total_rooms' => 45,
                'total_beds' => 180,
                'rent_per_bed' => 650.00,
                'amenities' => ['WiFi', 'Laundry', 'Kitchen', 'Common Room', 'Co-working Space', 'High-speed Internet', 'Security', 'Air Conditioning'],
                'images' => ['tech1.jpg', 'tech2.jpg', 'tech3.jpg'],
                'status' => 'active',
                'manager_name' => 'Alex Chen',
                'manager_phone' => '+1-555-0888',
                'manager_email' => 'alex@techhubresidence.com',
                'rules' => 'No smoking, No pets, Quiet hours 11 PM - 7 AM, Co-working space rules apply, Visitors must be registered',
                'check_in_time' => '15:00:00',
                'check_out_time' => '11:00:00',
            ]
        ];

        foreach ($hostels as $hostelData) {
            Hostel::create($hostelData);
        }
    }
}
