<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Intent;

class IntentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $intents = [
            // Authentication Module
            [
                'intent_name' => 'authenticate_user',
                'intent_api_url' => '/api/v1/auth/login',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['email', 'password'],
                'intent_description' => 'Login user and obtain access token',
                'module' => 'authentication',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'logout_user',
                'intent_api_url' => '/api/v1/auth/logout',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => [],
                'intent_description' => 'Invalidate user session and token',
                'module' => 'authentication',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_user_profile',
                'intent_api_url' => '/api/v1/auth/me',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => [],
                'intent_description' => 'Retrieve current authenticated user details',
                'module' => 'authentication',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'refresh_token',
                'intent_api_url' => '/api/v1/auth/refresh',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => [],
                'intent_description' => 'Generate new access token using refresh token',
                'module' => 'authentication',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'validate_token',
                'intent_api_url' => '/api/v1/auth/me',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => [],
                'intent_description' => 'Check if current token is valid and active',
                'module' => 'authentication',
                'requires_auth' => true,
            ],

            // Hostels Module
            [
                'intent_name' => 'list_hostels',
                'intent_api_url' => '/api/v1/hostels',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'search', 'status'],
                'intent_description' => 'Get all hostels with filtering and pagination',
                'module' => 'hostels',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_hostel',
                'intent_api_url' => '/api/v1/hostels',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['name', 'address', 'phone', 'email', 'description', 'check_in_time', 'check_out_time', 'rules', 'amenities'],
                'intent_description' => 'Add new hostel with complete details',
                'module' => 'hostels',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_hostel_details',
                'intent_api_url' => '/api/v1/hostels/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve specific hostel information',
                'module' => 'hostels',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_hostel',
                'intent_api_url' => '/api/v1/hostels/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'name', 'address', 'phone', 'email', 'description', 'check_in_time', 'check_out_time', 'rules', 'amenities'],
                'intent_description' => 'Modify existing hostel details',
                'module' => 'hostels',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_hostel',
                'intent_api_url' => '/api/v1/hostels/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove hostel with safety checks',
                'module' => 'hostels',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'search_hostels',
                'intent_api_url' => '/api/v1/hostels/search',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['query', 'location', 'amenities', 'limit'],
                'intent_description' => 'Find hostels by name, location, or criteria',
                'module' => 'hostels',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_hostel_stats',
                'intent_api_url' => '/api/v1/hostels/stats',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['hostel_id', 'period'],
                'intent_description' => 'Retrieve occupancy and performance metrics',
                'module' => 'hostels',
                'requires_auth' => false,
            ],

            // Tenants Module
            [
                'intent_name' => 'list_tenants',
                'intent_api_url' => '/api/v1/tenants',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'status', 'hostel_id', 'search'],
                'intent_description' => 'Get all tenants with filtering options',
                'module' => 'tenants',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_tenant',
                'intent_api_url' => '/api/v1/tenants',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['name', 'email', 'phone', 'date_of_birth', 'address', 'occupation', 'company', 'emergency_contact_name', 'emergency_contact_phone', 'id_proof_type', 'id_proof_number', 'move_in_date', 'monthly_rent', 'lease_start_date', 'lease_end_date'],
                'intent_description' => 'Register new tenant with profile',
                'module' => 'tenants',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_tenant_details',
                'intent_api_url' => '/api/v1/tenants/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve complete tenant information',
                'module' => 'tenants',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_tenant',
                'intent_api_url' => '/api/v1/tenants/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'name', 'email', 'phone', 'date_of_birth', 'address', 'occupation', 'company', 'emergency_contact_name', 'emergency_contact_phone', 'id_proof_type', 'id_proof_number', 'move_in_date', 'monthly_rent', 'lease_start_date', 'lease_end_date'],
                'intent_description' => 'Modify tenant profile and details',
                'module' => 'tenants',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_tenant',
                'intent_api_url' => '/api/v1/tenants/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove tenant with data cleanup',
                'module' => 'tenants',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'search_tenants',
                'intent_api_url' => '/api/v1/tenants/search',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['query', 'status', 'hostel_id', 'limit'],
                'intent_description' => 'Find tenants by name, email, or criteria',
                'module' => 'tenants',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'assign_bed',
                'intent_api_url' => '/api/v1/tenants/assign-bed',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['tenant_id', 'bed_id', 'assigned_from', 'assigned_until'],
                'intent_description' => 'Assign tenant to specific bed',
                'module' => 'tenants',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'release_bed',
                'intent_api_url' => '/api/v1/tenants/release-bed',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['tenant_id', 'bed_id', 'release_date'],
                'intent_description' => 'Remove tenant from bed assignment',
                'module' => 'tenants',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'verify_tenant',
                'intent_api_url' => '/api/v1/tenants/{id}/verify',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Mark tenant as verified',
                'module' => 'tenants',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_tenant_stats',
                'intent_api_url' => '/api/v1/tenants/stats',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['hostel_id', 'period'],
                'intent_description' => 'Retrieve tenant analytics and metrics',
                'module' => 'tenants',
                'requires_auth' => false,
            ],

            // Rooms & Beds Module
            [
                'intent_name' => 'list_rooms',
                'intent_api_url' => '/api/v1/rooms-beds/rooms',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'hostel_id', 'floor', 'type', 'status'],
                'intent_description' => 'Get all rooms with occupancy status',
                'module' => 'rooms_beds',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_room',
                'intent_api_url' => '/api/v1/rooms-beds/rooms',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['hostel_id', 'room_number', 'floor', 'type', 'capacity', 'amenities', 'status'],
                'intent_description' => 'Add new room to hostel',
                'module' => 'rooms_beds',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_room_details',
                'intent_api_url' => '/api/v1/rooms-beds/rooms/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve room information and beds',
                'module' => 'rooms_beds',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_room',
                'intent_api_url' => '/api/v1/rooms-beds/rooms/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'room_number', 'floor', 'type', 'capacity', 'amenities', 'status'],
                'intent_description' => 'Modify room details and configuration',
                'module' => 'rooms_beds',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_room',
                'intent_api_url' => '/api/v1/rooms-beds/rooms/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove room with safety checks',
                'module' => 'rooms_beds',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'list_beds',
                'intent_api_url' => '/api/v1/rooms-beds/beds',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'room_id', 'hostel_id', 'status'],
                'intent_description' => 'Get all beds with assignment status',
                'module' => 'rooms_beds',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_bed',
                'intent_api_url' => '/api/v1/rooms-beds/beds',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['room_id', 'bed_number', 'type', 'rent', 'status'],
                'intent_description' => 'Add new bed to room',
                'module' => 'rooms_beds',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_bed_details',
                'intent_api_url' => '/api/v1/rooms-beds/beds/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve bed information',
                'module' => 'rooms_beds',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_bed',
                'intent_api_url' => '/api/v1/rooms-beds/beds/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'bed_number', 'type', 'rent', 'status'],
                'intent_description' => 'Modify bed details',
                'module' => 'rooms_beds',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_bed',
                'intent_api_url' => '/api/v1/rooms-beds/beds/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove bed with safety checks',
                'module' => 'rooms_beds',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_occupancy_stats',
                'intent_api_url' => '/api/v1/rooms-beds/occupancy-stats',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['hostel_id', 'room_id', 'period'],
                'intent_description' => 'Retrieve occupancy analytics',
                'module' => 'rooms_beds',
                'requires_auth' => false,
            ],

            // Invoices Module
            [
                'intent_name' => 'list_invoices',
                'intent_api_url' => '/api/v1/invoices',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'tenant_id', 'status', 'date_from', 'date_to'],
                'intent_description' => 'Get all invoices with filtering',
                'module' => 'invoices',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_invoice',
                'intent_api_url' => '/api/v1/invoices',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['tenant_profile_id', 'invoice_date', 'due_date', 'items', 'notes'],
                'intent_description' => 'Generate new invoice',
                'module' => 'invoices',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_invoice_details',
                'intent_api_url' => '/api/v1/invoices/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve invoice with items and payments',
                'module' => 'invoices',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_invoice',
                'intent_api_url' => '/api/v1/invoices/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'invoice_date', 'due_date', 'notes'],
                'intent_description' => 'Modify invoice details',
                'module' => 'invoices',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_invoice',
                'intent_api_url' => '/api/v1/invoices/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove invoice with safety checks',
                'module' => 'invoices',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'search_invoices',
                'intent_api_url' => '/api/v1/invoices/search',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['query', 'tenant_id', 'status', 'date_from', 'date_to', 'limit'],
                'intent_description' => 'Find invoices by number, tenant, or criteria',
                'module' => 'invoices',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'add_payment',
                'intent_api_url' => '/api/v1/invoices/{id}/add-payment',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'amount', 'payment_method', 'payment_date', 'reference_number', 'notes'],
                'intent_description' => 'Record payment against invoice',
                'module' => 'invoices',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'mark_overdue',
                'intent_api_url' => '/api/v1/invoices/{id}/mark-overdue',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Mark invoice as overdue',
                'module' => 'invoices',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'generate_amenity_invoice',
                'intent_api_url' => '/api/v1/invoices/generate-amenity',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['tenant_profile_id', 'amenity_usage_records', 'invoice_date', 'due_date'],
                'intent_description' => 'Create invoice for amenity usage',
                'module' => 'invoices',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'add_invoice_item',
                'intent_api_url' => '/api/v1/invoices/{id}/add-item',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'description', 'quantity', 'unit_price', 'tax_rate'],
                'intent_description' => 'Add line item to invoice',
                'module' => 'invoices',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'update_invoice_item',
                'intent_api_url' => '/api/v1/invoices/{id}/update-item/{item_id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'item_id', 'description', 'quantity', 'unit_price', 'tax_rate'],
                'intent_description' => 'Modify invoice line item',
                'module' => 'invoices',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'remove_invoice_item',
                'intent_api_url' => '/api/v1/invoices/{id}/remove-item/{item_id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id', 'item_id'],
                'intent_description' => 'Remove line item from invoice',
                'module' => 'invoices',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_invoice_stats',
                'intent_api_url' => '/api/v1/invoices/stats',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['period', 'tenant_id', 'hostel_id'],
                'intent_description' => 'Retrieve invoice analytics',
                'module' => 'invoices',
                'requires_auth' => false,
            ],

            // Payments Module
            [
                'intent_name' => 'list_payments',
                'intent_api_url' => '/api/v1/payments',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'tenant_id', 'invoice_id', 'status', 'method', 'date_from', 'date_to'],
                'intent_description' => 'Get all payments with filtering',
                'module' => 'payments',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_payment',
                'intent_api_url' => '/api/v1/payments',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['tenant_profile_id', 'invoice_id', 'amount', 'payment_method', 'payment_date', 'reference_number', 'notes'],
                'intent_description' => 'Record new payment',
                'module' => 'payments',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_payment_details',
                'intent_api_url' => '/api/v1/payments/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve payment information',
                'module' => 'payments',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_payment',
                'intent_api_url' => '/api/v1/payments/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'amount', 'payment_method', 'payment_date', 'reference_number', 'notes'],
                'intent_description' => 'Modify payment details',
                'module' => 'payments',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_payment',
                'intent_api_url' => '/api/v1/payments/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove payment with safety checks',
                'module' => 'payments',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'search_payments',
                'intent_api_url' => '/api/v1/payments/search',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['query', 'tenant_id', 'invoice_id', 'status', 'method', 'date_from', 'date_to', 'limit'],
                'intent_description' => 'Find payments by tenant, invoice, or criteria',
                'module' => 'payments',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'verify_payment',
                'intent_api_url' => '/api/v1/payments/{id}/verify',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'verified_by'],
                'intent_description' => 'Mark payment as verified',
                'module' => 'payments',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'cancel_payment',
                'intent_api_url' => '/api/v1/payments/{id}/cancel',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'cancellation_reason'],
                'intent_description' => 'Cancel payment and reverse invoice updates',
                'module' => 'payments',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_tenant_payment_summary',
                'intent_api_url' => '/api/v1/payments/tenant-summary/{tenant_id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['tenant_id', 'period'],
                'intent_description' => 'Get payment summary for tenant',
                'module' => 'payments',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_invoice_payment_summary',
                'intent_api_url' => '/api/v1/payments/invoice-summary/{invoice_id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['invoice_id'],
                'intent_description' => 'Get payment summary for invoice',
                'module' => 'payments',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_payment_stats',
                'intent_api_url' => '/api/v1/payments/stats',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['period', 'tenant_id', 'hostel_id'],
                'intent_description' => 'Retrieve payment analytics',
                'module' => 'payments',
                'requires_auth' => false,
            ],

            // Amenities Module
            [
                'intent_name' => 'list_basic_amenities',
                'intent_api_url' => '/api/v1/amenities',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'hostel_id', 'status'],
                'intent_description' => 'Get all basic amenities',
                'module' => 'amenities',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_basic_amenity',
                'intent_api_url' => '/api/v1/amenities',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['name', 'description', 'icon', 'hostel_ids'],
                'intent_description' => 'Add new basic amenity',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_basic_amenity_details',
                'intent_api_url' => '/api/v1/amenities/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve amenity information',
                'module' => 'amenities',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_basic_amenity',
                'intent_api_url' => '/api/v1/amenities/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'name', 'description', 'icon', 'hostel_ids'],
                'intent_description' => 'Modify amenity details',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_basic_amenity',
                'intent_api_url' => '/api/v1/amenities/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove amenity',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'list_paid_amenities',
                'intent_api_url' => '/api/v1/amenities/paid',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'category', 'billing_type', 'status'],
                'intent_description' => 'Get all paid amenities',
                'module' => 'amenities',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_paid_amenity',
                'intent_api_url' => '/api/v1/amenities/paid',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['name', 'description', 'category', 'billing_type', 'price', 'unit', 'availability_schedule', 'max_usage_per_day', 'status'],
                'intent_description' => 'Add new paid amenity',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_paid_amenity_details',
                'intent_api_url' => '/api/v1/amenities/paid/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve paid amenity information',
                'module' => 'amenities',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_paid_amenity',
                'intent_api_url' => '/api/v1/amenities/paid/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'name', 'description', 'category', 'billing_type', 'price', 'unit', 'availability_schedule', 'max_usage_per_day', 'status'],
                'intent_description' => 'Modify paid amenity details',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_paid_amenity',
                'intent_api_url' => '/api/v1/amenities/paid/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove paid amenity',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'list_tenant_subscriptions',
                'intent_api_url' => '/api/v1/amenities/subscriptions',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'tenant_id', 'amenity_id', 'status'],
                'intent_description' => 'Get tenant amenity subscriptions',
                'module' => 'amenities',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'subscribe_tenant',
                'intent_api_url' => '/api/v1/amenities/subscribe',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['tenant_profile_id', 'paid_amenity_id', 'custom_price', 'start_date', 'end_date'],
                'intent_description' => 'Subscribe tenant to amenity',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'update_subscription',
                'intent_api_url' => '/api/v1/amenities/subscriptions/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'custom_price', 'start_date', 'end_date'],
                'intent_description' => 'Modify subscription details',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'suspend_subscription',
                'intent_api_url' => '/api/v1/amenities/subscriptions/{id}/suspend',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'reason'],
                'intent_description' => 'Temporarily suspend subscription',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'reactivate_subscription',
                'intent_api_url' => '/api/v1/amenities/subscriptions/{id}/reactivate',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Reactivate suspended subscription',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'terminate_subscription',
                'intent_api_url' => '/api/v1/amenities/subscriptions/{id}/terminate',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'reason'],
                'intent_description' => 'Permanently end subscription',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'list_usage_records',
                'intent_api_url' => '/api/v1/amenities/usage',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'tenant_id', 'amenity_id', 'date_from', 'date_to'],
                'intent_description' => 'Get amenity usage records',
                'module' => 'amenities',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'record_usage',
                'intent_api_url' => '/api/v1/amenities/record-usage',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['tenant_amenity_id', 'usage_date', 'quantity', 'unit_price', 'notes'],
                'intent_description' => 'Record amenity usage',
                'module' => 'amenities',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_tenant_usage_summary',
                'intent_api_url' => '/api/v1/amenities/tenant-usage-summary/{tenant_id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['tenant_id', 'period'],
                'intent_description' => 'Get usage summary for tenant',
                'module' => 'amenities',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'search_amenities',
                'intent_api_url' => '/api/v1/amenities/search',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['query', 'type', 'category', 'limit'],
                'intent_description' => 'Find amenities by name or criteria',
                'module' => 'amenities',
                'requires_auth' => false,
            ],

            // Users Module
            [
                'intent_name' => 'list_users',
                'intent_api_url' => '/api/v1/users',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'status', 'is_tenant', 'role_id'],
                'intent_description' => 'Get all users with filtering',
                'module' => 'users',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_user',
                'intent_api_url' => '/api/v1/users',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['name', 'email', 'password', 'phone', 'status', 'avatar', 'is_tenant', 'is_super_admin'],
                'intent_description' => 'Add new user account',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_user_details',
                'intent_api_url' => '/api/v1/users/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve user information',
                'module' => 'users',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_user',
                'intent_api_url' => '/api/v1/users/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'name', 'email', 'phone', 'status', 'avatar', 'is_tenant', 'is_super_admin'],
                'intent_description' => 'Modify user details',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_user',
                'intent_api_url' => '/api/v1/users/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove user account',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'assign_role',
                'intent_api_url' => '/api/v1/users/{id}/assign-role',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'role_id'],
                'intent_description' => 'Assign role to user',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'remove_role',
                'intent_api_url' => '/api/v1/users/{id}/remove-role',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'role_id'],
                'intent_description' => 'Remove role from user',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'suspend_user',
                'intent_api_url' => '/api/v1/users/{id}/suspend',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'reason'],
                'intent_description' => 'Suspend user account',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'activate_user',
                'intent_api_url' => '/api/v1/users/{id}/activate',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Activate suspended account',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'list_roles',
                'intent_api_url' => '/api/v1/users/roles',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'is_system'],
                'intent_description' => 'Get all available roles',
                'module' => 'users',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_role',
                'intent_api_url' => '/api/v1/users/roles',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['name', 'slug', 'description', 'is_system'],
                'intent_description' => 'Add new role',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_role_details',
                'intent_api_url' => '/api/v1/users/roles/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve role information',
                'module' => 'users',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_role',
                'intent_api_url' => '/api/v1/users/roles/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'name', 'slug', 'description', 'is_system'],
                'intent_description' => 'Modify role details',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_role',
                'intent_api_url' => '/api/v1/users/roles/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove role',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'list_permissions',
                'intent_api_url' => '/api/v1/users/permissions',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'module', 'is_system'],
                'intent_description' => 'Get all permissions',
                'module' => 'users',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_permission',
                'intent_api_url' => '/api/v1/users/permissions',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['name', 'slug', 'description', 'module', 'is_system'],
                'intent_description' => 'Add new permission',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_permission_details',
                'intent_api_url' => '/api/v1/users/permissions/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve permission information',
                'module' => 'users',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_permission',
                'intent_api_url' => '/api/v1/users/permissions/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'name', 'slug', 'description', 'module', 'is_system'],
                'intent_description' => 'Modify permission details',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_permission',
                'intent_api_url' => '/api/v1/users/permissions/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove permission',
                'module' => 'users',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_user_stats',
                'intent_api_url' => '/api/v1/users/stats',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['period', 'role_id'],
                'intent_description' => 'Retrieve user analytics',
                'module' => 'users',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_available_modules',
                'intent_api_url' => '/api/v1/users/modules',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => [],
                'intent_description' => 'Get system modules',
                'module' => 'users',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'search_users',
                'intent_api_url' => '/api/v1/users/search',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['query', 'status', 'is_tenant', 'role_id', 'limit'],
                'intent_description' => 'Find users by name, email, or criteria',
                'module' => 'users',
                'requires_auth' => false,
            ],

            // Enquiries Module
            [
                'intent_name' => 'list_enquiries',
                'intent_api_url' => '/api/v1/enquiries',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'status', 'priority', 'enquiry_type', 'assigned_to'],
                'intent_description' => 'Get all enquiries with filtering',
                'module' => 'enquiries',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_enquiry',
                'intent_api_url' => '/api/v1/enquiries',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['name', 'email', 'phone', 'enquiry_type', 'subject', 'message', 'priority', 'source', 'metadata'],
                'intent_description' => 'Add new enquiry',
                'module' => 'enquiries',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_enquiry_details',
                'intent_api_url' => '/api/v1/enquiries/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve enquiry information',
                'module' => 'enquiries',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_enquiry',
                'intent_api_url' => '/api/v1/enquiries/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'name', 'email', 'phone', 'enquiry_type', 'subject', 'message', 'status', 'priority', 'admin_notes', 'assigned_to'],
                'intent_description' => 'Modify enquiry details',
                'module' => 'enquiries',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_enquiry',
                'intent_api_url' => '/api/v1/enquiries/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove enquiry',
                'module' => 'enquiries',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'search_enquiries',
                'intent_api_url' => '/api/v1/enquiries/search',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['query', 'status', 'priority', 'enquiry_type', 'limit'],
                'intent_description' => 'Find enquiries by name, email, or criteria',
                'module' => 'enquiries',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'assign_enquiry',
                'intent_api_url' => '/api/v1/enquiries/{id}/assign',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'assigned_to'],
                'intent_description' => 'Assign enquiry to user',
                'module' => 'enquiries',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'resolve_enquiry',
                'intent_api_url' => '/api/v1/enquiries/{id}/resolve',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'resolution_notes'],
                'intent_description' => 'Mark enquiry as resolved',
                'module' => 'enquiries',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'close_enquiry',
                'intent_api_url' => '/api/v1/enquiries/{id}/close',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'closure_notes'],
                'intent_description' => 'Close enquiry',
                'module' => 'enquiries',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'convert_to_tenant',
                'intent_api_url' => '/api/v1/enquiries/{id}/convert-to-tenant',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'tenant_data'],
                'intent_description' => 'Convert enquiry to tenant profile',
                'module' => 'enquiries',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_enquiry_stats',
                'intent_api_url' => '/api/v1/enquiries/stats',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['period', 'assigned_to'],
                'intent_description' => 'Retrieve enquiry analytics',
                'module' => 'enquiries',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_enquiry_sources',
                'intent_api_url' => '/api/v1/enquiries/sources',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['period'],
                'intent_description' => 'Get enquiry source breakdown',
                'module' => 'enquiries',
                'requires_auth' => false,
            ],

            // Notifications Module
            [
                'intent_name' => 'list_notifications',
                'intent_api_url' => '/api/v1/notifications',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['page', 'limit', 'status', 'type', 'recipient_email'],
                'intent_description' => 'Get all notifications with filtering',
                'module' => 'notifications',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'create_notification',
                'intent_api_url' => '/api/v1/notifications',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['type', 'title', 'message', 'recipient_email', 'recipient_name', 'data', 'scheduled_at', 'notifiable_type', 'notifiable_id'],
                'intent_description' => 'Add new notification',
                'module' => 'notifications',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_notification_details',
                'intent_api_url' => '/api/v1/notifications/{id}',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retrieve notification information',
                'module' => 'notifications',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'update_notification',
                'intent_api_url' => '/api/v1/notifications/{id}',
                'intent_api_type' => 'PUT',
                'intent_api_parameters' => ['id', 'type', 'title', 'message', 'recipient_email', 'recipient_name', 'data', 'scheduled_at'],
                'intent_description' => 'Modify notification details',
                'module' => 'notifications',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'delete_notification',
                'intent_api_url' => '/api/v1/notifications/{id}',
                'intent_api_type' => 'DELETE',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Remove notification',
                'module' => 'notifications',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'search_notifications',
                'intent_api_url' => '/api/v1/notifications/search',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['query', 'status', 'type', 'recipient_email', 'limit'],
                'intent_description' => 'Find notifications by content or criteria',
                'module' => 'notifications',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'mark_as_sent',
                'intent_api_url' => '/api/v1/notifications/{id}/mark-sent',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Mark notification as sent',
                'module' => 'notifications',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'mark_as_failed',
                'intent_api_url' => '/api/v1/notifications/{id}/mark-failed',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id', 'error_message'],
                'intent_description' => 'Mark notification as failed',
                'module' => 'notifications',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'retry_notification',
                'intent_api_url' => '/api/v1/notifications/{id}/retry',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Retry failed notification',
                'module' => 'notifications',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'cancel_notification',
                'intent_api_url' => '/api/v1/notifications/{id}/cancel',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Cancel pending notification',
                'module' => 'notifications',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'send_now',
                'intent_api_url' => '/api/v1/notifications/{id}/send-now',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['id'],
                'intent_description' => 'Send notification immediately',
                'module' => 'notifications',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_notification_stats',
                'intent_api_url' => '/api/v1/notifications/stats',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['period', 'type'],
                'intent_description' => 'Retrieve notification analytics',
                'module' => 'notifications',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_scheduled_notifications',
                'intent_api_url' => '/api/v1/notifications/scheduled',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['limit'],
                'intent_description' => 'Get notifications ready to send',
                'module' => 'notifications',
                'requires_auth' => false,
            ],

            // Dashboard Module
            [
                'intent_name' => 'get_dashboard_overview',
                'intent_api_url' => '/api/v1/dashboard/overview',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => [],
                'intent_description' => 'Retrieve comprehensive dashboard summary',
                'module' => 'dashboard',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_financial_dashboard',
                'intent_api_url' => '/api/v1/dashboard/financial',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['period'],
                'intent_description' => 'Get financial analytics and metrics',
                'module' => 'dashboard',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_occupancy_dashboard',
                'intent_api_url' => '/api/v1/dashboard/occupancy',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['hostel_id', 'period'],
                'intent_description' => 'Get occupancy analytics and trends',
                'module' => 'dashboard',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_tenant_analytics',
                'intent_api_url' => '/api/v1/dashboard/tenants',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['hostel_id', 'period'],
                'intent_description' => 'Get tenant analytics and demographics',
                'module' => 'dashboard',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_amenity_analytics',
                'intent_api_url' => '/api/v1/dashboard/amenities',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['period'],
                'intent_description' => 'Get amenity usage analytics',
                'module' => 'dashboard',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_enquiry_analytics',
                'intent_api_url' => '/api/v1/dashboard/enquiries',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['period'],
                'intent_description' => 'Get enquiry analytics and conversion',
                'module' => 'dashboard',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_notification_analytics',
                'intent_api_url' => '/api/v1/dashboard/notifications',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['period'],
                'intent_description' => 'Get notification delivery analytics',
                'module' => 'dashboard',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_system_health',
                'intent_api_url' => '/api/v1/dashboard/system-health',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => [],
                'intent_description' => 'Get system health and performance metrics',
                'module' => 'dashboard',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'get_dashboard_widgets',
                'intent_api_url' => '/api/v1/dashboard/widgets',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => [],
                'intent_description' => 'Get available widgets and user preferences',
                'module' => 'dashboard',
                'requires_auth' => false,
            ],
            [
                'intent_name' => 'customize_dashboard',
                'intent_api_url' => '/api/v1/dashboard/widgets',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['widgets', 'layout'],
                'intent_description' => 'Configure user-specific dashboard layout',
                'module' => 'dashboard',
                'requires_auth' => true,
            ],

            // Chat Module
            [
                'intent_name' => 'send_chat_message',
                'intent_api_url' => '/api/v1/chat/send-message',
                'intent_api_type' => 'POST',
                'intent_api_parameters' => ['message', 'conversation_id'],
                'intent_description' => 'Send message to AI chat assistant',
                'module' => 'chat',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_chat_history',
                'intent_api_url' => '/api/v1/chat/history',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => ['conversation_id'],
                'intent_description' => 'Retrieve chat conversation history',
                'module' => 'chat',
                'requires_auth' => true,
            ],
            [
                'intent_name' => 'get_chat_user_info',
                'intent_api_url' => '/api/v1/chat/user-info',
                'intent_api_type' => 'GET',
                'intent_api_parameters' => [],
                'intent_description' => 'Get user context for chat',
                'module' => 'chat',
                'requires_auth' => true,
            ],
        ];

        foreach ($intents as $intent) {
            Intent::create($intent);
        }
    }
}
